doc-warnings: no
test-warnings: no
strictness: high
max-line-length: 180

python-targets:
    - 2
    - 3
pylint:
  disable:
    - too-many-lines
    - invalid-name
    - unused-variable
    - attribute-defined-outside-init

pep8:
  disable:
    - N803
    - N806

pyflakes:
  disable:
    - F811
